### ISSUE TITLE
Black Squares

### ISSUE THREAD

**Issue by kermankohli** [ra1028/RACollectionViewReorderableTripletLayout#3]
After reordering squares, about 2-3 go black. Using iOS 8 Xcode 6.

**Comment by Tb1985** [comment]
Hi everybody, trying to solve the same problem, any advice you can give me would be highly appreciate!

Thanks!

**Comment by Tb1985** [comment]
Ok solved. Seems iOS 8 has some problem setting the "autoresizingMask" property.

Commenting this line:
_imageView.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;
in RACollectionViewCell will solve the image size issue.

Hope this may help you!

**Comment by kermankohli** [comment]
Thanks for that! Also do you have an any idea on how you can change the size of the small square so you could have 2  or 1 items in a row?

**Comment by Tb1985** [comment]
Hi, no problem ;)
You find pretty much everything about the cell layout in the RACollectionViewTripletLayout file.
The large size and small size are derived and generated in this function:
- (UICollectionViewLayoutAttributes *)layoutAttributesForItemAtIndexPath:(NSIndexPath *)indexPath

in detail, here:

 //cellSize
    CGFloat largeCellSideLength = (2.f \* (_collectionViewSize.width) - _itemSpacing) / 3.f;
    CGFloat smallCellSideLength = (largeCellSideLength - _itemSpacing) / 2.f;

```
_largeCellSize = CGSizeMake(largeCellSideLength, largeCellSideLength);
_smallCellSize = CGSizeMake(smallCellSideLength, smallCellSideLength);

if ([self.delegate respondsToSelector:@selector(collectionView:sizeForLargeItemsInSection:)]) {
    if (!CGSizeEqualToSize([self.delegate collectionView:self.collectionView sizeForLargeItemsInSection:indexPath.section], RACollectionViewTripletLayoutStyleSquare)) {
        _largeCellSize = [self.delegate collectionView:self.collectionView sizeForLargeItemsInSection:indexPath.section];
        _smallCellSize = CGSizeMake(_collectionViewSize.width - _largeCellSize.width - _itemSpacing - _insets.left - _insets.right, (_largeCellSize.height / 2.f) - (_itemSpacing / 2.f));
    }
}
```

just play around with it in order to achieve the layout you're looking for.

**Comment by kermankohli** [comment]
Hmm I tried having a play around with the code in that method but didn’t really get anywhere...
—

**Comment by ra1028** [comment]
I'm sorry to leave this issue as long time.
I fixed this issue and updated pods.
Please, check my new reorderable layout. https://github.com/ra1028/RAReorderableLayout
