### ISSUE TITLE
iOS8 breaks 

### ISSUE THREAD

**Issue by soltrinox** [ra1028/RACollectionViewReorderableTripletLayout#4]
in iOS 8  
the RACollectionViewTripletLayout.m

Method : layoutAttributesForElementsInRect

prevents display of the Collection View cells and fails when checking the following logic.

LINE: 135

if (CGRectEqualToRect(_oldRect, rect) && !shouldUpdate) {
        return _oldArray;
    }

Testing it in iOS 7 it works as is. But after setting the "shouldUpdate" to true it finally works in iOS 8.

Must be a bug in the way the values set ??
I commented out the check and forced it to generate a new Layout attributes.

Works now in my app. Not sure if this was a local problem for me but something to look into.

Cheers.

**Comment by ra1028** [comment]
I'm sorry to leave this issue as long time.
I fixed this issue and updated pods.
Please, check my new reorderable layout. https://github.com/ra1028/RAReorderableLayout
