### ISSUE TITLE
Is it possible to use custom layout instead of Triplet?

### ISSUE THREAD

**Issue by efimovdk** [ra1028/RACollectionViewReorderableTripletLayout#9]
This is great work, but almost useless if it can't be applied for other layouts. But I believe it can be applied. Which way?

**Comment by ra1028** [comment]
@dimefim [Check it out !!](https://github.com/ra1028/RAReorderableLayout)

**Comment by dimefim** [comment]
@ra1028 Yeah, but how to use swift files in obj-c project?
